Repository prgrms-fe-devcourse/NFE1_2_3_TurtleNeck, pull requests merged in 2024-11, with the labels that each got.

#54 :sparkles: Feat: 좋아요 버튼 화면 구현 ( #11 )
  client/src/app/post/components/LikeButton.jsx
  client/src/app/post/components/LikeButton.module.scss
  client/src/app/post/page.jsx
Labels: ✨ Feat

#58 [Feat] API 연결 설정
  client/src/utils/api.js
  server/middleware.js
Labels: ✨ Feat

#59 ✨Feat: 로그인 페이지 구현#47
  client/package-lock.json
  client/package.json
  client/src/app/ClientProvider.js
  client/src/app/api/auth/[...nextauth]/route.js
  client/src/app/login/login.module.scss
  client/src/app/login/page.jsx
  client/src/app/utils/test.js
  client/src/utils/api.js
  server/app/api/auth/[id]/route.js
  server/app/api/auth/login/route.js
  server/app/api/auth/route.js
Labels: ✨ Feat

#60 ✨ 프롤로그 섹션 api 연결 구현 (#55)
  client/src/app/components/MainPostCard/MainPostCard.jsx
  client/src/app/page.jsx
  client/src/utils/api.js
Labels: ✨ Feat

#62 :sparkle: Feat: 게시글 상세보기 API 연동 학인 #56
  client/src/app/post/[id]/page.jsx
  client/src/app/post/[id]/post.module.scss
  client/src/app/post/components/LikeButton.module.scss
  client/src/app/post/page.jsx
Labels: ✨ Feat

#64 🐛 Fix: 프롤로그섹션 api연결 문제 수정 (#63)
  server/app/api/post/route.js
Labels: 🐛 Fix

#68 :sparkles: Feat: 좋아요 기능 완성 #61 + 추가 스타일링 작업
  client/src/app/api/like/[id]/route.js
  client/src/app/post/[id]/page.jsx
  client/src/app/post/[id]/post.module.scss
  client/src/app/post/components/LikeButton.jsx
  client/src/utils/api.js
Labels: ✨ Feat, 🌈 Design

#69 ✨ Feat: 메인포스트에 해당하는 상세페이지 링크 연결 (#65)
  client/src/app/components/MainPostCard/MainPostCard.jsx
  client/src/app/components/MainPostCard/MainPostCard.module.scss
  client/src/utils/api.js
Labels: ✨ Feat

#71 ✨Feat: 필터 기능을 위한 API 추가 #70
  client/src/utils/api.js
  server/app/api/category/[id]/route.js
  server/app/api/category/route.js
Labels: ✨ Feat

#73 Feat/#34 게시글 카드 APi 연동 완료
  client/src/app/components/PostCard/PostCard.jsx
  client/src/app/components/PostCard/PostCard.module.scss
  client/src/app/page.jsx
  client/src/app/page.module.css
  client/src/utils/api.js
Labels: ✨ Feat, 🌈 Design

#72 ✨ feat: 대표이미지를 제외한 글작성 기능 완료(#26)
  client/public/images/arrow-left.png
  client/public/images/selectArrow.png
  client/src/app/components/navigation/index.jsx
  client/src/app/write/dist/write.module.css
  client/src/app/write/editor.css
  client/src/app/write/page.jsx
  client/src/app/write/write.module.scss
  client/src/utils/api.js
  client/src/utils/dist/api.dev.js
  server/app/api/post/dist/route.dev.js
  server/app/api/post/route.js
  server/app/db/models/dist/post.dev.js
  server/app/db/models/post.js
Labels: ✨ Feat

#76 #74 #15 게시글 관리 버튼 및 상세보기 스타일링
  client/src/app/post/[id]/page.jsx
  client/src/app/post/[id]/post.module.scss
  package-lock.json
  package.json
Labels: ✨ Feat, 🌈 Design

#78 Feat✨: 블로그 기본 설정 및 카테고리 관리 기능 구현 #40, #39
  client/src/app/admin/components/BlogSettings.jsx
  client/src/app/admin/page.jsx
  client/src/app/post/[id]/page.jsx
  server/app/api/admin/[type]/route.js
  server/app/api/admin/route.js
  server/app/db/models/comment.js
Labels: ✨ Feat

#79 ✨Feat: 댓글 API 엔드포인트 기능 추가 #35
  client/src/utils/api.js
  server/app/api/comment/[id]/route.js
  server/app/api/comment/route.js
Labels: ✨ Feat

#80 ✨Feat: 댓글 컴포넌트 기능 추가 및 css 수정 #2
  client/package-lock.json
  client/package.json
  client/src/app/api/test.js
  client/src/app/globals.css
  client/src/app/post/[id]/page.jsx
  client/src/app/post/components/CommentSection.module.scss
  client/src/app/post/components/comments.jsx
  package-lock.json
  package.json
Labels: ✨ Feat

#85 Feat/#74
  client/package-lock.json
  client/package.json
  client/src/app/post/[id]/page.jsx
  client/src/app/post/[id]/post.module.scss
Labels: 🌈 Design

#89 🐛Fix: 댓글 수정 오류 및 스타일 변경#83
  client/src/app/admin/components/Comments.jsx
  client/src/app/assets/imgs/dots-horizontal.png
  client/src/app/assets/imgs/message-square.png
  client/src/app/post/components/CommentSection.module.scss
  client/src/app/post/components/comments.jsx
  server/app/api/comment/[id]/route.js
Labels: 🐛 Fix

#90 🌈 Design: 댓글 수정폼 레이아웃 변경 #38
  client/src/app/post/components/comments.jsx
Labels: 🌈 Design

#92 Feat/#86 좋아요 API 오류 정정
  client/src/app/api/like/[id]/route.js
  client/src/app/post/[id]/page.jsx
  client/src/app/post/components/LikeButton.jsx
  client/src/app/post/components/LikeButton.module.scss
Labels: 🐛 Fix

#96 ✨ Feat: 기타 css 및 마크업 수정 (#95)
  client/src/app/globals.css
  client/src/app/page.jsx
  client/src/app/page.module.css
Labels: ✨ Feat

#98 ✨Feat: 댓글 관리 페이지#91
  client/src/app/admin/components/Comments.jsx
  client/src/app/admin/components/Comments.module.scss
  client/src/app/admin/page.jsx
  client/src/utils/api.js
  server/app/api/admin/comments/route.js
Labels: ✨ Feat

#105 ✨Feat: 카테고리 관리 페이지 구현#41
  client/src/app/admin/components/BlogSettings.jsx
  client/src/app/admin/components/BlogSettings.module.scss
  client/src/app/admin/components/CategorySettings.jsx
  client/src/app/admin/components/CategorySettings.module.scss
  client/src/app/admin/page.jsx
  client/src/app/components/MainPostCard/MainPostCard.jsx
  client/src/app/components/navigation/navigation.module.scss
  client/src/app/page.module.css
  client/src/utils/api.js
  server/app/api/admin/mainPostCategory/route.js
  server/app/api/category/route.js
  server/app/api/post/route.js
  server/app/db/dbConnect.js
  server/app/db/models/auth.js
Labels: ✨ Feat
